# do not check code copied into the project
# do not check sha code, lots of hashing false positives
# do not check testing data
[files]
extend-exclude = [
  "config/*",
  "src/common/libev/*",
  "src/common/libccan/*",
  "src/common/liblsd/*",
  "src/common/libtomlc99/*",
  "src/common/libczmqcontainers/*",
  "src/bindings/python/flux/utils/parsedatetime/*",
  "src/bindings/python/flux/utils/dataclasses/*",
  "t/sharness.sh",
  "src/common/libutil/sha1.c",
  "src/common/libutil/test/sha1.c",
  "src/common/libutil/test/blobref.c",
  "src/common/libmissing/*.[ch]",
  "t/hwloc-data/*",
  "doc/test/spell.en.pws",
  "t/resource/resource.eventlog.*",
  "t/sharness",
]

[default.extend-words]
# in hwloc output
hsi = "hsi"
# commonly used names/variables that aren't typos
fo = "fo"
ba = "ba"
inout = "inout"
trun = "trun"
fullset = "fullset"
mone = "mone"
requestor = "requestor"
requestors = "requestors"
clen = "clen"
WRONLY = "WRONLY"
TOU = "TOU"
